-- Adds AI question generation, questionnaire answer storage, and revamp result persistence
-- to the onboarding_submissions table as part of the onboarding flow redesign.

ALTER TABLE public.onboarding_submissions
  ADD COLUMN IF NOT EXISTS parsed_resume         jsonb,
  ADD COLUMN IF NOT EXISTS ai_questions          jsonb,
  ADD COLUMN IF NOT EXISTS questionnaire_answers jsonb,
  ADD COLUMN IF NOT EXISTS revamp_result         jsonb;

COMMENT ON COLUMN public.onboarding_submissions.parsed_resume IS
  'AI-structured resume JSON (from parseResumeText) generated at form-submission time';

COMMENT ON COLUMN public.onboarding_submissions.ai_questions IS
  'RevampQuestion[] generated by AI at form-submission time, enriched with work experience + preferences context';

COMMENT ON COLUMN public.onboarding_submissions.questionnaire_answers IS
  'Record<questionId, answer> submitted by user after reviewing AI questions';

COMMENT ON COLUMN public.onboarding_submissions.revamp_result IS
  '{ revampedResume, changes, compiledPdfUrl } produced by the AI revamp call, stored for returning user sessions';
